# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jon's Security Blog
email: jon@jondb.io 
description: >
  Writing about information security
logo: "/assets/images/schematic.gif"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jonsecurity.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Jon'
bio: >
  Hello - how are you? Welcome to my site.
  With over 18 years of experience, I'll try to help you.
author_image: "/assets/images/stickman.jpg"
twitter_username: _jondb_ 
github_username:  jondb

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
